name: Code Quality - azkey-bot-roumu

on:
  push:
    paths: 
      - 'azkey-bot-roumu/**'
      - '.github/workflows/lint.yml'
  pull_request:
    paths: 
      - 'azkey-bot-roumu/**'
      - '.github/workflows/lint.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        cd azkey-bot-roumu
        uv sync
        uv add --dev ruff

    - name: Run Ruff linter
      run: |
        cd azkey-bot-roumu
        uv run ruff check azkey_bot_roumu/ --output-format=github

    - name: Run Ruff formatter check
      run: |
        cd azkey-bot-roumu
        uv run ruff format azkey_bot_roumu/ --check
